<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BecarioServicioSocialRepository extends EntityRepository {
    
    
    public function allBecarioServicioSocial() {
         return $this->getEntityManager()
        ->createQueryBuilder()
        ->select('s')
        ->from('AppBundle:Serviciosocial', 's')
        ->leftJoin('s.idexpbecario','u')
        //->where('u.id = sb.idusuario')
        ->getQuery()
        ->getResult();
    }


}