<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaRepository extends EntityRepository {
    
    
    public function allCuenta() {
         return $this->getEntityManager()
        ->createQueryBuilder()
        ->select('c')
        ->from('AppBundle:Cuenta', 'c')
        ->leftJoin('c.idusuario','u')
        //->where('u.id = m.idusuario')
        ->getQuery()
        ->getResult();
    }


}