<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoRepository extends EntityRepository {
    
    
    public function allMovimiento() {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT m FROM AppBundle:Movimiento m '
                               
                        )
                        ->getResult();
    }


}
