<?php

namespace AppBundle\Repository;

/**
 * pagocolaboracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pagocolaboracionRepository extends \Doctrine\ORM\EntityRepository
{
}
