<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProgramarPublicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramarPublicacionRepository extends EntityRepository {
    
    
    public function allProgramarPublicacion() {
         return $this->getEntityManager()
        ->createQueryBuilder()
        ->select('pp')
        ->from('AppBundle:Programarpublicacion', 'pp')
        ->leftJoin('pp.idusuario','u')

        //->where('u.id = m.idusuario')
        ->getQuery()
        ->getResult();
    }


}
