<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicarContenidoRepository extends EntityRepository {
    
    
    public function allPublicarContenido() {
         return $this->getEntityManager()
        ->createQueryBuilder()
        ->select('p')
        ->from('AppBundle:Publicarcontenido', 'p')
        ->leftJoin('p.idusuario','u')
        //->where('u.id = m.idusuario')
        ->getQuery()
        ->getResult();
    }


}
