<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository {

    public function findAllRoles() {
        return $this->getEntityManager()
        ->createQueryBuilder()
        ->select('m')
        ->from('AppBundle:Role', 'm')
        //->leftJoin('m.idusuario','u')
        //->where('u.id = m.idusuario')
        ->getQuery()
        ->getResult();
    }

   

}
