<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SolicitudesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudPatrocinadorRepository extends EntityRepository {

       public function patrocinadores() {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('s')
                        ->from('AppBundle:Solicitudpatrocinador', 's')
                        ->leftJoin('s.idusuario', 'u')
                        //->where('u.id = m.idusuario')
                        ->getQuery()
                        ->getResult();
    }
    }
