<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudBecarioRepository extends EntityRepository {
    
    
    public function allSolicitudBecario() {
         return $this->getEntityManager()
        ->createQueryBuilder()
        ->select('s')
        ->from('AppBundle:Solicitudbecario', 's')
        ->leftJoin('s.idusuario','u')
        //->where('u.id = sb.idusuario')
        ->getQuery()
        ->getResult();
    }


}