<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SolicitudesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudesRepository extends EntityRepository {

    public function aprobadosrepo() {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT s FROM AppBundle:Solicitudbecario s WHERE s.estadosolibecario=1'
                        )
                        ->getResult();
    }

     public function rechazadosrepo() {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT s FROM AppBundle:Solicitudbecario s WHERE s.estadosolibecario=0'
                        )
                        ->getResult();
    }
    
}