<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Proyectoserviciosocial extends \AppBundle\Entity\Proyectoserviciosocial implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Proyectoserviciosocial' . "\0" . 'idproyectservisocial', '' . "\0" . 'AppBundle\\Entity\\Proyectoserviciosocial' . "\0" . 'nombreproyecto', '' . "\0" . 'AppBundle\\Entity\\Proyectoserviciosocial' . "\0" . 'descripcionproyecto', '' . "\0" . 'AppBundle\\Entity\\Proyectoserviciosocial' . "\0" . 'encargadoproyecto', '' . "\0" . 'AppBundle\\Entity\\Proyectoserviciosocial' . "\0" . 'lugarproyecto', '' . "\0" . 'AppBundle\\Entity\\Proyectoserviciosocial' . "\0" . 'estadoproyecto'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Proyectoserviciosocial' . "\0" . 'idproyectservisocial', '' . "\0" . 'AppBundle\\Entity\\Proyectoserviciosocial' . "\0" . 'nombreproyecto', '' . "\0" . 'AppBundle\\Entity\\Proyectoserviciosocial' . "\0" . 'descripcionproyecto', '' . "\0" . 'AppBundle\\Entity\\Proyectoserviciosocial' . "\0" . 'encargadoproyecto', '' . "\0" . 'AppBundle\\Entity\\Proyectoserviciosocial' . "\0" . 'lugarproyecto', '' . "\0" . 'AppBundle\\Entity\\Proyectoserviciosocial' . "\0" . 'estadoproyecto'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Proyectoserviciosocial $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNombreproyecto($nombreproyecto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreproyecto', [$nombreproyecto]);

        return parent::setNombreproyecto($nombreproyecto);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreproyecto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreproyecto', []);

        return parent::getNombreproyecto();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionproyecto($descripcionproyecto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionproyecto', [$descripcionproyecto]);

        return parent::setDescripcionproyecto($descripcionproyecto);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionproyecto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionproyecto', []);

        return parent::getDescripcionproyecto();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncargadoproyecto($encargadoproyecto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncargadoproyecto', [$encargadoproyecto]);

        return parent::setEncargadoproyecto($encargadoproyecto);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncargadoproyecto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncargadoproyecto', []);

        return parent::getEncargadoproyecto();
    }

    /**
     * {@inheritDoc}
     */
    public function setLugarproyecto($lugarproyecto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLugarproyecto', [$lugarproyecto]);

        return parent::setLugarproyecto($lugarproyecto);
    }

    /**
     * {@inheritDoc}
     */
    public function getLugarproyecto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugarproyecto', []);

        return parent::getLugarproyecto();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoproyecto($estadoproyecto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoproyecto', [$estadoproyecto]);

        return parent::setEstadoproyecto($estadoproyecto);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoproyecto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoproyecto', []);

        return parent::getEstadoproyecto();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdproyectservisocial()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdproyectservisocial();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdproyectservisocial', []);

        return parent::getIdproyectservisocial();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
