<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Universidad extends \AppBundle\Entity\Universidad implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Universidad' . "\0" . 'iduniversidad', '' . "\0" . 'AppBundle\\Entity\\Universidad' . "\0" . 'nombreuniversidad', '' . "\0" . 'AppBundle\\Entity\\Universidad' . "\0" . 'estadouniversidad', '' . "\0" . 'AppBundle\\Entity\\Universidad' . "\0" . 'idcarrera', '' . "\0" . 'AppBundle\\Entity\\Universidad' . "\0" . 'carcarrera'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Universidad' . "\0" . 'iduniversidad', '' . "\0" . 'AppBundle\\Entity\\Universidad' . "\0" . 'nombreuniversidad', '' . "\0" . 'AppBundle\\Entity\\Universidad' . "\0" . 'estadouniversidad', '' . "\0" . 'AppBundle\\Entity\\Universidad' . "\0" . 'idcarrera', '' . "\0" . 'AppBundle\\Entity\\Universidad' . "\0" . 'carcarrera'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Universidad $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNombreuniversidad($nombreuniversidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreuniversidad', [$nombreuniversidad]);

        return parent::setNombreuniversidad($nombreuniversidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreuniversidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreuniversidad', []);

        return parent::getNombreuniversidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadouniversidad($estadouniversidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadouniversidad', [$estadouniversidad]);

        return parent::setEstadouniversidad($estadouniversidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadouniversidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadouniversidad', []);

        return parent::getEstadouniversidad();
    }

    /**
     * {@inheritDoc}
     */
    public function getIduniversidad()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIduniversidad();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIduniversidad', []);

        return parent::getIduniversidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarcarrera(\AppBundle\Entity\Carrera $carcarrera = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarcarrera', [$carcarrera]);

        return parent::setCarcarrera($carcarrera);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarcarrera()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarcarrera', []);

        return parent::getCarcarrera();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcarrera(\AppBundle\Entity\Carrera $idcarrera = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcarrera', [$idcarrera]);

        return parent::setIdcarrera($idcarrera);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcarrera()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcarrera', []);

        return parent::getIdcarrera();
    }

}
