<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Solicitudbecario extends \AppBundle\Entity\Solicitudbecario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'idsolibecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'telefonosolibecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'ingresossolifamiliabecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'miembrossolifamiliabecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'tiposolicasabecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'carrerasoliestudiarbecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'universidadsolibecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'montosolimatriculabecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'cuotasolimensualbecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'duracionsolicarrerabecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'trabajosolibecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'docsoliidentidadbecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'aniosoliingresobecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'aniosolifinalizacionbecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'cantsolihermanosbecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'nomsolipadrebecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'nomsolimadrebecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'telsoliemergenciabecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'telsolipersonalbecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'miembrossolifamilibecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'direccionsolibecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'estadosolibecario'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'idsolibecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'telefonosolibecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'ingresossolifamiliabecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'miembrossolifamiliabecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'tiposolicasabecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'carrerasoliestudiarbecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'universidadsolibecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'montosolimatriculabecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'cuotasolimensualbecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'duracionsolicarrerabecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'trabajosolibecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'docsoliidentidadbecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'aniosoliingresobecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'aniosolifinalizacionbecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'cantsolihermanosbecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'nomsolipadrebecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'nomsolimadrebecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'telsoliemergenciabecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'telsolipersonalbecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'miembrossolifamilibecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'direccionsolibecario', '' . "\0" . 'AppBundle\\Entity\\Solicitudbecario' . "\0" . 'estadosolibecario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Solicitudbecario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setTelefonosolibecario($telefonosolibecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonosolibecario', [$telefonosolibecario]);

        return parent::setTelefonosolibecario($telefonosolibecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonosolibecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonosolibecario', []);

        return parent::getTelefonosolibecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIngresossolifamiliabecario($ingresossolifamiliabecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIngresossolifamiliabecario', [$ingresossolifamiliabecario]);

        return parent::setIngresossolifamiliabecario($ingresossolifamiliabecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIngresossolifamiliabecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIngresossolifamiliabecario', []);

        return parent::getIngresossolifamiliabecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setMiembrossolifamiliabecario($miembrossolifamiliabecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMiembrossolifamiliabecario', [$miembrossolifamiliabecario]);

        return parent::setMiembrossolifamiliabecario($miembrossolifamiliabecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getMiembrossolifamiliabecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMiembrossolifamiliabecario', []);

        return parent::getMiembrossolifamiliabecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setTiposolicasabecario($tiposolicasabecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTiposolicasabecario', [$tiposolicasabecario]);

        return parent::setTiposolicasabecario($tiposolicasabecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getTiposolicasabecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTiposolicasabecario', []);

        return parent::getTiposolicasabecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarrerasoliestudiarbecario($carrerasoliestudiarbecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarrerasoliestudiarbecario', [$carrerasoliestudiarbecario]);

        return parent::setCarrerasoliestudiarbecario($carrerasoliestudiarbecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarrerasoliestudiarbecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarrerasoliestudiarbecario', []);

        return parent::getCarrerasoliestudiarbecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUniversidadsolibecario($universidadsolibecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniversidadsolibecario', [$universidadsolibecario]);

        return parent::setUniversidadsolibecario($universidadsolibecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUniversidadsolibecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniversidadsolibecario', []);

        return parent::getUniversidadsolibecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontosolimatriculabecario($montosolimatriculabecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontosolimatriculabecario', [$montosolimatriculabecario]);

        return parent::setMontosolimatriculabecario($montosolimatriculabecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontosolimatriculabecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontosolimatriculabecario', []);

        return parent::getMontosolimatriculabecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setCuotasolimensualbecario($cuotasolimensualbecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCuotasolimensualbecario', [$cuotasolimensualbecario]);

        return parent::setCuotasolimensualbecario($cuotasolimensualbecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getCuotasolimensualbecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuotasolimensualbecario', []);

        return parent::getCuotasolimensualbecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuracionsolicarrerabecario($duracionsolicarrerabecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuracionsolicarrerabecario', [$duracionsolicarrerabecario]);

        return parent::setDuracionsolicarrerabecario($duracionsolicarrerabecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuracionsolicarrerabecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuracionsolicarrerabecario', []);

        return parent::getDuracionsolicarrerabecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrabajosolibecario($trabajosolibecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrabajosolibecario', [$trabajosolibecario]);

        return parent::setTrabajosolibecario($trabajosolibecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrabajosolibecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrabajosolibecario', []);

        return parent::getTrabajosolibecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocsoliidentidadbecario($docsoliidentidadbecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocsoliidentidadbecario', [$docsoliidentidadbecario]);

        return parent::setDocsoliidentidadbecario($docsoliidentidadbecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocsoliidentidadbecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocsoliidentidadbecario', []);

        return parent::getDocsoliidentidadbecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setAniosoliingresobecario($aniosoliingresobecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAniosoliingresobecario', [$aniosoliingresobecario]);

        return parent::setAniosoliingresobecario($aniosoliingresobecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getAniosoliingresobecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAniosoliingresobecario', []);

        return parent::getAniosoliingresobecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setAniosolifinalizacionbecario($aniosolifinalizacionbecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAniosolifinalizacionbecario', [$aniosolifinalizacionbecario]);

        return parent::setAniosolifinalizacionbecario($aniosolifinalizacionbecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getAniosolifinalizacionbecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAniosolifinalizacionbecario', []);

        return parent::getAniosolifinalizacionbecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantsolihermanosbecario($cantsolihermanosbecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantsolihermanosbecario', [$cantsolihermanosbecario]);

        return parent::setCantsolihermanosbecario($cantsolihermanosbecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantsolihermanosbecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantsolihermanosbecario', []);

        return parent::getCantsolihermanosbecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomsolipadrebecario($nomsolipadrebecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomsolipadrebecario', [$nomsolipadrebecario]);

        return parent::setNomsolipadrebecario($nomsolipadrebecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomsolipadrebecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomsolipadrebecario', []);

        return parent::getNomsolipadrebecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomsolimadrebecario($nomsolimadrebecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomsolimadrebecario', [$nomsolimadrebecario]);

        return parent::setNomsolimadrebecario($nomsolimadrebecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomsolimadrebecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomsolimadrebecario', []);

        return parent::getNomsolimadrebecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelsoliemergenciabecario($telsoliemergenciabecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelsoliemergenciabecario', [$telsoliemergenciabecario]);

        return parent::setTelsoliemergenciabecario($telsoliemergenciabecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelsoliemergenciabecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelsoliemergenciabecario', []);

        return parent::getTelsoliemergenciabecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelsolipersonalbecario($telsolipersonalbecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelsolipersonalbecario', [$telsolipersonalbecario]);

        return parent::setTelsolipersonalbecario($telsolipersonalbecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelsolipersonalbecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelsolipersonalbecario', []);

        return parent::getTelsolipersonalbecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setMiembrossolifamilibecario($miembrossolifamilibecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMiembrossolifamilibecario', [$miembrossolifamilibecario]);

        return parent::setMiembrossolifamilibecario($miembrossolifamilibecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getMiembrossolifamilibecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMiembrossolifamilibecario', []);

        return parent::getMiembrossolifamilibecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccionsolibecario($direccionsolibecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccionsolibecario', [$direccionsolibecario]);

        return parent::setDireccionsolibecario($direccionsolibecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccionsolibecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccionsolibecario', []);

        return parent::getDireccionsolibecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadosolibecario($estadosolibecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadosolibecario', [$estadosolibecario]);

        return parent::setEstadosolibecario($estadosolibecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadosolibecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadosolibecario', []);

        return parent::getEstadosolibecario();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdsolibecario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdsolibecario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsolibecario', []);

        return parent::getIdsolibecario();
    }

}
