<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Serviciosocial extends \AppBundle\Entity\Serviciosocial implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Serviciosocial' . "\0" . 'idserviciosocial', '' . "\0" . 'AppBundle\\Entity\\Serviciosocial' . "\0" . 'idexpbecario', '' . "\0" . 'AppBundle\\Entity\\Serviciosocial' . "\0" . 'fechaaprovacionservicio', '' . "\0" . 'AppBundle\\Entity\\Serviciosocial' . "\0" . 'fechainicioservicio', '' . "\0" . 'AppBundle\\Entity\\Serviciosocial' . "\0" . 'fechafinservicio', '' . "\0" . 'AppBundle\\Entity\\Serviciosocial' . "\0" . 'estadoservicio', '' . "\0" . 'AppBundle\\Entity\\Serviciosocial' . "\0" . 'idproyectservisocial'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Serviciosocial' . "\0" . 'idserviciosocial', '' . "\0" . 'AppBundle\\Entity\\Serviciosocial' . "\0" . 'idexpbecario', '' . "\0" . 'AppBundle\\Entity\\Serviciosocial' . "\0" . 'fechaaprovacionservicio', '' . "\0" . 'AppBundle\\Entity\\Serviciosocial' . "\0" . 'fechainicioservicio', '' . "\0" . 'AppBundle\\Entity\\Serviciosocial' . "\0" . 'fechafinservicio', '' . "\0" . 'AppBundle\\Entity\\Serviciosocial' . "\0" . 'estadoservicio', '' . "\0" . 'AppBundle\\Entity\\Serviciosocial' . "\0" . 'idproyectservisocial'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Serviciosocial $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdexpbecario($idexpbecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdexpbecario', [$idexpbecario]);

        return parent::setIdexpbecario($idexpbecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdexpbecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdexpbecario', []);

        return parent::getIdexpbecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaaprovacionservicio($fechaaprovacionservicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaaprovacionservicio', [$fechaaprovacionservicio]);

        return parent::setFechaaprovacionservicio($fechaaprovacionservicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaaprovacionservicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaaprovacionservicio', []);

        return parent::getFechaaprovacionservicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechainicioservicio($fechainicioservicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechainicioservicio', [$fechainicioservicio]);

        return parent::setFechainicioservicio($fechainicioservicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechainicioservicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechainicioservicio', []);

        return parent::getFechainicioservicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechafinservicio($fechafinservicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechafinservicio', [$fechafinservicio]);

        return parent::setFechafinservicio($fechafinservicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechafinservicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechafinservicio', []);

        return parent::getFechafinservicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoservicio($estadoservicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoservicio', [$estadoservicio]);

        return parent::setEstadoservicio($estadoservicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoservicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoservicio', []);

        return parent::getEstadoservicio();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdserviciosocial()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdserviciosocial();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdserviciosocial', []);

        return parent::getIdserviciosocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdproyectservisocial(\AppBundle\Entity\Proyectoserviciosocial $idproyectservisocial = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdproyectservisocial', [$idproyectservisocial]);

        return parent::setIdproyectservisocial($idproyectservisocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdproyectservisocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdproyectservisocial', []);

        return parent::getIdproyectservisocial();
    }

}
