<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Publicacioncontenido extends \AppBundle\Entity\Publicacioncontenido implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'idcontenido', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'titulo', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'subtitulo', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'descripcioncontenido', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'fechacontenido', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'estadocontenido', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'contenido_picture_file', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'contenidoPicture', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'idusuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'idcontenido', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'titulo', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'subtitulo', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'descripcioncontenido', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'fechacontenido', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'estadocontenido', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'contenido_picture_file', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'contenidoPicture', '' . "\0" . 'AppBundle\\Entity\\Publicacioncontenido' . "\0" . 'idusuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Publicacioncontenido $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', []);

        return parent::getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuario(\SalexUserBundle\Entity\User $idusuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuario', [$idusuario]);

        return parent::setIdusuario($idusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtitulo($subtitulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtitulo', [$subtitulo]);

        return parent::setSubtitulo($subtitulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenidoPictureFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenidoPictureFile', []);

        return parent::getContenidoPictureFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenidoPictureFile(\Symfony\Component\HttpFoundation\File\File $contenido_picture_file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenidoPictureFile', [$contenido_picture_file]);

        return parent::setContenidoPictureFile($contenido_picture_file);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenidoPicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenidoPicture', []);

        return parent::getContenidoPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenidoPicture($contenidoPicture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenidoPicture', [$contenidoPicture]);

        return parent::setContenidoPicture($contenidoPicture);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtitulo', []);

        return parent::getSubtitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcioncontenido($descripcioncontenido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcioncontenido', [$descripcioncontenido]);

        return parent::setDescripcioncontenido($descripcioncontenido);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcioncontenido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcioncontenido', []);

        return parent::getDescripcioncontenido();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechacontenido($fechacontenido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechacontenido', [$fechacontenido]);

        return parent::setFechacontenido($fechacontenido);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechacontenido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechacontenido', []);

        return parent::getFechacontenido();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadocontenido($estadocontenido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadocontenido', [$estadocontenido]);

        return parent::setEstadocontenido($estadocontenido);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadocontenido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadocontenido', []);

        return parent::getEstadocontenido();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcontenido()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdcontenido();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcontenido', []);

        return parent::getIdcontenido();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
