<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Programarpublicacion extends \AppBundle\Entity\Programarpublicacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Programarpublicacion' . "\0" . 'idpublicacion', '' . "\0" . 'AppBundle\\Entity\\Programarpublicacion' . "\0" . 'fechapublicacion', '' . "\0" . 'AppBundle\\Entity\\Programarpublicacion' . "\0" . 'horapublicacion', '' . "\0" . 'AppBundle\\Entity\\Programarpublicacion' . "\0" . 'estadopulicacion', '' . "\0" . 'AppBundle\\Entity\\Programarpublicacion' . "\0" . 'idcontenido', '' . "\0" . 'AppBundle\\Entity\\Programarpublicacion' . "\0" . 'idusuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Programarpublicacion' . "\0" . 'idpublicacion', '' . "\0" . 'AppBundle\\Entity\\Programarpublicacion' . "\0" . 'fechapublicacion', '' . "\0" . 'AppBundle\\Entity\\Programarpublicacion' . "\0" . 'horapublicacion', '' . "\0" . 'AppBundle\\Entity\\Programarpublicacion' . "\0" . 'estadopulicacion', '' . "\0" . 'AppBundle\\Entity\\Programarpublicacion' . "\0" . 'idcontenido', '' . "\0" . 'AppBundle\\Entity\\Programarpublicacion' . "\0" . 'idusuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Programarpublicacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', []);

        return parent::getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuario(\SalexUserBundle\Entity\User $idusuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuario', [$idusuario]);

        return parent::setIdusuario($idusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setFechapublicacion($fechapublicacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechapublicacion', [$fechapublicacion]);

        return parent::setFechapublicacion($fechapublicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechapublicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechapublicacion', []);

        return parent::getFechapublicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorapublicacion($horapublicacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorapublicacion', [$horapublicacion]);

        return parent::setHorapublicacion($horapublicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorapublicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorapublicacion', []);

        return parent::getHorapublicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadopulicacion($estadopulicacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadopulicacion', [$estadopulicacion]);

        return parent::setEstadopulicacion($estadopulicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadopulicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadopulicacion', []);

        return parent::getEstadopulicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpublicacion()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdpublicacion();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpublicacion', []);

        return parent::getIdpublicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcontenido(\AppBundle\Entity\Publicacioncontenido $idcontenido = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcontenido', [$idcontenido]);

        return parent::setIdcontenido($idcontenido);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcontenido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcontenido', []);

        return parent::getIdcontenido();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
