<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cheque extends \AppBundle\Entity\Cheque implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'idcheque', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'idexpbecario', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'codigocheque', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'montocheque', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'destinatariocheque', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'bancocheque', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'fechaemisioncheque', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'estadocheque', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'idemisor'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'idcheque', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'idexpbecario', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'codigocheque', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'montocheque', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'destinatariocheque', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'bancocheque', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'fechaemisioncheque', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'estadocheque', '' . "\0" . 'AppBundle\\Entity\\Cheque' . "\0" . 'idemisor'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cheque $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdexpbecario($idexpbecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdexpbecario', [$idexpbecario]);

        return parent::setIdexpbecario($idexpbecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdexpbecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdexpbecario', []);

        return parent::getIdexpbecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigocheque($codigocheque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigocheque', [$codigocheque]);

        return parent::setCodigocheque($codigocheque);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigocheque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigocheque', []);

        return parent::getCodigocheque();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontocheque($montocheque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontocheque', [$montocheque]);

        return parent::setMontocheque($montocheque);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontocheque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontocheque', []);

        return parent::getMontocheque();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestinatariocheque($destinatariocheque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestinatariocheque', [$destinatariocheque]);

        return parent::setDestinatariocheque($destinatariocheque);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestinatariocheque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestinatariocheque', []);

        return parent::getDestinatariocheque();
    }

    /**
     * {@inheritDoc}
     */
    public function setBancocheque($bancocheque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBancocheque', [$bancocheque]);

        return parent::setBancocheque($bancocheque);
    }

    /**
     * {@inheritDoc}
     */
    public function getBancocheque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBancocheque', []);

        return parent::getBancocheque();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaemisioncheque($fechaemisioncheque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaemisioncheque', [$fechaemisioncheque]);

        return parent::setFechaemisioncheque($fechaemisioncheque);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaemisioncheque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaemisioncheque', []);

        return parent::getFechaemisioncheque();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadocheque($estadocheque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadocheque', [$estadocheque]);

        return parent::setEstadocheque($estadocheque);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadocheque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadocheque', []);

        return parent::getEstadocheque();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcheque()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdcheque();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcheque', []);

        return parent::getIdcheque();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdemisor(\AppBundle\Entity\Emisor $idemisor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdemisor', [$idemisor]);

        return parent::setIdemisor($idemisor);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdemisor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdemisor', []);

        return parent::getIdemisor();
    }

}
