<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bitacoraserviciosocial extends \AppBundle\Entity\Bitacoraserviciosocial implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Bitacoraserviciosocial' . "\0" . 'idbitacora', '' . "\0" . 'AppBundle\\Entity\\Bitacoraserviciosocial' . "\0" . 'detallebitacora', '' . "\0" . 'AppBundle\\Entity\\Bitacoraserviciosocial' . "\0" . 'fechabitacora', '' . "\0" . 'AppBundle\\Entity\\Bitacoraserviciosocial' . "\0" . 'horainiciobitacora', '' . "\0" . 'AppBundle\\Entity\\Bitacoraserviciosocial' . "\0" . 'horafinbitacora', '' . "\0" . 'AppBundle\\Entity\\Bitacoraserviciosocial' . "\0" . 'descripcionactividadbitacora', '' . "\0" . 'AppBundle\\Entity\\Bitacoraserviciosocial' . "\0" . 'estadobitacora', '' . "\0" . 'AppBundle\\Entity\\Bitacoraserviciosocial' . "\0" . 'idserviciosocial'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Bitacoraserviciosocial' . "\0" . 'idbitacora', '' . "\0" . 'AppBundle\\Entity\\Bitacoraserviciosocial' . "\0" . 'detallebitacora', '' . "\0" . 'AppBundle\\Entity\\Bitacoraserviciosocial' . "\0" . 'fechabitacora', '' . "\0" . 'AppBundle\\Entity\\Bitacoraserviciosocial' . "\0" . 'horainiciobitacora', '' . "\0" . 'AppBundle\\Entity\\Bitacoraserviciosocial' . "\0" . 'horafinbitacora', '' . "\0" . 'AppBundle\\Entity\\Bitacoraserviciosocial' . "\0" . 'descripcionactividadbitacora', '' . "\0" . 'AppBundle\\Entity\\Bitacoraserviciosocial' . "\0" . 'estadobitacora', '' . "\0" . 'AppBundle\\Entity\\Bitacoraserviciosocial' . "\0" . 'idserviciosocial'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Bitacoraserviciosocial $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setDetallebitacora($detallebitacora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetallebitacora', [$detallebitacora]);

        return parent::setDetallebitacora($detallebitacora);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetallebitacora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetallebitacora', []);

        return parent::getDetallebitacora();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechabitacora($fechabitacora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechabitacora', [$fechabitacora]);

        return parent::setFechabitacora($fechabitacora);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechabitacora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechabitacora', []);

        return parent::getFechabitacora();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorainiciobitacora($horainiciobitacora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorainiciobitacora', [$horainiciobitacora]);

        return parent::setHorainiciobitacora($horainiciobitacora);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorainiciobitacora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorainiciobitacora', []);

        return parent::getHorainiciobitacora();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorafinbitacora($horafinbitacora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorafinbitacora', [$horafinbitacora]);

        return parent::setHorafinbitacora($horafinbitacora);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorafinbitacora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorafinbitacora', []);

        return parent::getHorafinbitacora();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionactividadbitacora($descripcionactividadbitacora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionactividadbitacora', [$descripcionactividadbitacora]);

        return parent::setDescripcionactividadbitacora($descripcionactividadbitacora);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionactividadbitacora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionactividadbitacora', []);

        return parent::getDescripcionactividadbitacora();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadobitacora($estadobitacora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadobitacora', [$estadobitacora]);

        return parent::setEstadobitacora($estadobitacora);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadobitacora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadobitacora', []);

        return parent::getEstadobitacora();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdbitacora()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdbitacora();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdbitacora', []);

        return parent::getIdbitacora();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdserviciosocial(\AppBundle\Entity\Serviciosocial $idserviciosocial = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdserviciosocial', [$idserviciosocial]);

        return parent::setIdserviciosocial($idserviciosocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdserviciosocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdserviciosocial', []);

        return parent::getIdserviciosocial();
    }

}
