<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pagocolaboracion extends \AppBundle\Entity\Pagocolaboracion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'apellido', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'monto', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'pago', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'idpagocolaboracion', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'descripcionpago', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'descripcioncolaboracion', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'pagorealizado', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'idusuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'apellido', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'monto', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'pago', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'idpagocolaboracion', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'descripcionpago', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'descripcioncolaboracion', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'pagorealizado', '' . "\0" . 'AppBundle\\Entity\\Pagocolaboracion' . "\0" . 'idusuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pagocolaboracion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', []);

        return parent::getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuario(\SalexUserBundle\Entity\User $idusuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuario', [$idusuario]);

        return parent::setIdusuario($idusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpagocolaboracion()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdpagocolaboracion();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpagocolaboracion', []);

        return parent::getIdpagocolaboracion();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionpago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionpago', []);

        return parent::getDescripcionpago();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpagocolaboracion($idpagocolaboracion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpagocolaboracion', [$idpagocolaboracion]);

        return parent::setIdpagocolaboracion($idpagocolaboracion);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionpago($descripcionpago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionpago', [$descripcionpago]);

        return parent::setDescripcionpago($descripcionpago);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', []);

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getMonto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonto', []);

        return parent::getMonto();
    }

    /**
     * {@inheritDoc}
     */
    public function getPago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPago', []);

        return parent::getPago();
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido($apellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', [$apellido]);

        return parent::setApellido($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setMonto($monto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonto', [$monto]);

        return parent::setMonto($monto);
    }

    /**
     * {@inheritDoc}
     */
    public function setPago($pago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPago', [$pago]);

        return parent::setPago($pago);
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha(\DateTime $fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcioncolaboracion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcioncolaboracion', []);

        return parent::getDescripcioncolaboracion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcioncolaboracion($descripcioncolaboracion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcioncolaboracion', [$descripcioncolaboracion]);

        return parent::setDescripcioncolaboracion($descripcioncolaboracion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagorealizado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagorealizado', []);

        return parent::getPagorealizado();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagorealizado($pagorealizado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagorealizado', [$pagorealizado]);

        return parent::setPagorealizado($pagorealizado);
    }

}
