<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Actividad extends \AppBundle\Entity\Actividad implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Actividad' . "\0" . 'idactividad', '' . "\0" . 'AppBundle\\Entity\\Actividad' . "\0" . 'nomactividad', '' . "\0" . 'AppBundle\\Entity\\Actividad' . "\0" . 'fechaactividad', '' . "\0" . 'AppBundle\\Entity\\Actividad' . "\0" . 'descripcionactividad', '' . "\0" . 'AppBundle\\Entity\\Actividad' . "\0" . 'estadoactividad', '' . "\0" . 'AppBundle\\Entity\\Actividad' . "\0" . 'requisito'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Actividad' . "\0" . 'idactividad', '' . "\0" . 'AppBundle\\Entity\\Actividad' . "\0" . 'nomactividad', '' . "\0" . 'AppBundle\\Entity\\Actividad' . "\0" . 'fechaactividad', '' . "\0" . 'AppBundle\\Entity\\Actividad' . "\0" . 'descripcionactividad', '' . "\0" . 'AppBundle\\Entity\\Actividad' . "\0" . 'estadoactividad', '' . "\0" . 'AppBundle\\Entity\\Actividad' . "\0" . 'requisito'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Actividad $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNomactividad($nomactividad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomactividad', [$nomactividad]);

        return parent::setNomactividad($nomactividad);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomactividad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomactividad', []);

        return parent::getNomactividad();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaactividad($fechaactividad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaactividad', [$fechaactividad]);

        return parent::setFechaactividad($fechaactividad);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaactividad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaactividad', []);

        return parent::getFechaactividad();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionactividad($descripcionactividad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionactividad', [$descripcionactividad]);

        return parent::setDescripcionactividad($descripcionactividad);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionactividad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionactividad', []);

        return parent::getDescripcionactividad();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoactividad($estadoactividad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoactividad', [$estadoactividad]);

        return parent::setEstadoactividad($estadoactividad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoactividad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoactividad', []);

        return parent::getEstadoactividad();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequisito($requisito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequisito', [$requisito]);

        return parent::setRequisito($requisito);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequisito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequisito', []);

        return parent::getRequisito();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdactividad()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdactividad();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdactividad', []);

        return parent::getIdactividad();
    }

}
