<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Materia extends \AppBundle\Entity\Materia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Materia' . "\0" . 'idmateria', '' . "\0" . 'AppBundle\\Entity\\Materia' . "\0" . 'nombremateria', '' . "\0" . 'AppBundle\\Entity\\Materia' . "\0" . 'unidadesvalorativasmateria', '' . "\0" . 'AppBundle\\Entity\\Materia' . "\0" . 'notamateria', '' . "\0" . 'AppBundle\\Entity\\Materia' . "\0" . 'aniomateria', '' . "\0" . 'AppBundle\\Entity\\Materia' . "\0" . 'numciclomateria', '' . "\0" . 'AppBundle\\Entity\\Materia' . "\0" . 'estadomateria', '' . "\0" . 'AppBundle\\Entity\\Materia' . "\0" . 'idinscripcion'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Materia' . "\0" . 'idmateria', '' . "\0" . 'AppBundle\\Entity\\Materia' . "\0" . 'nombremateria', '' . "\0" . 'AppBundle\\Entity\\Materia' . "\0" . 'unidadesvalorativasmateria', '' . "\0" . 'AppBundle\\Entity\\Materia' . "\0" . 'notamateria', '' . "\0" . 'AppBundle\\Entity\\Materia' . "\0" . 'aniomateria', '' . "\0" . 'AppBundle\\Entity\\Materia' . "\0" . 'numciclomateria', '' . "\0" . 'AppBundle\\Entity\\Materia' . "\0" . 'estadomateria', '' . "\0" . 'AppBundle\\Entity\\Materia' . "\0" . 'idinscripcion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Materia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNombremateria($nombremateria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombremateria', [$nombremateria]);

        return parent::setNombremateria($nombremateria);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombremateria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombremateria', []);

        return parent::getNombremateria();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidadesvalorativasmateria($unidadesvalorativasmateria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidadesvalorativasmateria', [$unidadesvalorativasmateria]);

        return parent::setUnidadesvalorativasmateria($unidadesvalorativasmateria);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidadesvalorativasmateria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidadesvalorativasmateria', []);

        return parent::getUnidadesvalorativasmateria();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotamateria($notamateria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotamateria', [$notamateria]);

        return parent::setNotamateria($notamateria);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotamateria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotamateria', []);

        return parent::getNotamateria();
    }

    /**
     * {@inheritDoc}
     */
    public function setAniomateria($aniomateria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAniomateria', [$aniomateria]);

        return parent::setAniomateria($aniomateria);
    }

    /**
     * {@inheritDoc}
     */
    public function getAniomateria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAniomateria', []);

        return parent::getAniomateria();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumciclomateria($numciclomateria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumciclomateria', [$numciclomateria]);

        return parent::setNumciclomateria($numciclomateria);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumciclomateria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumciclomateria', []);

        return parent::getNumciclomateria();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadomateria($estadomateria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadomateria', [$estadomateria]);

        return parent::setEstadomateria($estadomateria);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadomateria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadomateria', []);

        return parent::getEstadomateria();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmateria()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdmateria();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmateria', []);

        return parent::getIdmateria();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdinscripcion(\AppBundle\Entity\Inscripcion $idinscripcion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdinscripcion', [$idinscripcion]);

        return parent::setIdinscripcion($idinscripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdinscripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdinscripcion', []);

        return parent::getIdinscripcion();
    }

}
