<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Inventario extends \AppBundle\Entity\Inventario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Inventario' . "\0" . 'idinventario', '' . "\0" . 'AppBundle\\Entity\\Inventario' . "\0" . 'idexpbecario', '' . "\0" . 'AppBundle\\Entity\\Inventario' . "\0" . 'cantidadinventario', '' . "\0" . 'AppBundle\\Entity\\Inventario' . "\0" . 'fechainventario', '' . "\0" . 'AppBundle\\Entity\\Inventario' . "\0" . 'idmovinv', '' . "\0" . 'AppBundle\\Entity\\Inventario' . "\0" . 'idinsumo'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Inventario' . "\0" . 'idinventario', '' . "\0" . 'AppBundle\\Entity\\Inventario' . "\0" . 'idexpbecario', '' . "\0" . 'AppBundle\\Entity\\Inventario' . "\0" . 'cantidadinventario', '' . "\0" . 'AppBundle\\Entity\\Inventario' . "\0" . 'fechainventario', '' . "\0" . 'AppBundle\\Entity\\Inventario' . "\0" . 'idmovinv', '' . "\0" . 'AppBundle\\Entity\\Inventario' . "\0" . 'idinsumo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Inventario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdexpbecario($idexpbecario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdexpbecario', [$idexpbecario]);

        return parent::setIdexpbecario($idexpbecario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdexpbecario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdexpbecario', []);

        return parent::getIdexpbecario();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadinventario($cantidadinventario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadinventario', [$cantidadinventario]);

        return parent::setCantidadinventario($cantidadinventario);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadinventario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadinventario', []);

        return parent::getCantidadinventario();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechainventario($fechainventario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechainventario', [$fechainventario]);

        return parent::setFechainventario($fechainventario);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechainventario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechainventario', []);

        return parent::getFechainventario();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdinventario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdinventario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdinventario', []);

        return parent::getIdinventario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdinsumo(\AppBundle\Entity\Insumo $idinsumo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdinsumo', [$idinsumo]);

        return parent::setIdinsumo($idinsumo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdinsumo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdinsumo', []);

        return parent::getIdinsumo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmovinv(\AppBundle\Entity\Movimientoinventario $idmovinv = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmovinv', [$idmovinv]);

        return parent::setIdmovinv($idmovinv);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmovinv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmovinv', []);

        return parent::getIdmovinv();
    }

}
