<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Carrera extends \AppBundle\Entity\Carrera implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Carrera' . "\0" . 'idcarrera', '' . "\0" . 'AppBundle\\Entity\\Carrera' . "\0" . 'nomcarrera', '' . "\0" . 'AppBundle\\Entity\\Carrera' . "\0" . 'descripcioncarrera', '' . "\0" . 'AppBundle\\Entity\\Carrera' . "\0" . 'estadocarrera', '' . "\0" . 'AppBundle\\Entity\\Carrera' . "\0" . 'idmateria', '' . "\0" . 'AppBundle\\Entity\\Carrera' . "\0" . 'iduniversidad'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Carrera' . "\0" . 'idcarrera', '' . "\0" . 'AppBundle\\Entity\\Carrera' . "\0" . 'nomcarrera', '' . "\0" . 'AppBundle\\Entity\\Carrera' . "\0" . 'descripcioncarrera', '' . "\0" . 'AppBundle\\Entity\\Carrera' . "\0" . 'estadocarrera', '' . "\0" . 'AppBundle\\Entity\\Carrera' . "\0" . 'idmateria', '' . "\0" . 'AppBundle\\Entity\\Carrera' . "\0" . 'iduniversidad'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Carrera $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNomcarrera($nomcarrera)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomcarrera', [$nomcarrera]);

        return parent::setNomcarrera($nomcarrera);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomcarrera()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomcarrera', []);

        return parent::getNomcarrera();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcioncarrera($descripcioncarrera)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcioncarrera', [$descripcioncarrera]);

        return parent::setDescripcioncarrera($descripcioncarrera);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcioncarrera()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcioncarrera', []);

        return parent::getDescripcioncarrera();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadocarrera($estadocarrera)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadocarrera', [$estadocarrera]);

        return parent::setEstadocarrera($estadocarrera);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadocarrera()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadocarrera', []);

        return parent::getEstadocarrera();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcarrera()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdcarrera();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcarrera', []);

        return parent::getIdcarrera();
    }

    /**
     * {@inheritDoc}
     */
    public function setIduniversidad(\AppBundle\Entity\Universidad $iduniversidad = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIduniversidad', [$iduniversidad]);

        return parent::setIduniversidad($iduniversidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getIduniversidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIduniversidad', []);

        return parent::getIduniversidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmateria(\AppBundle\Entity\Materia $idmateria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmateria', [$idmateria]);

        return parent::setIdmateria($idmateria);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmateria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmateria', []);

        return parent::getIdmateria();
    }

}
