<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Movimiento extends \AppBundle\Entity\Movimiento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'idmov', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'descripcionmov', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'monto', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'estadomov', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'idtipomov', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'idcuenta', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'comprobante_file', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'comprobante', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'idusuario', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'updateAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'idmov', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'descripcionmov', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'monto', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'estadomov', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'idtipomov', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'idcuenta', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'comprobante_file', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'comprobante', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'idusuario', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\Movimiento' . "\0" . 'updateAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Movimiento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getComprobanteFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComprobanteFile', []);

        return parent::getComprobanteFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setComprobanteFile(\Symfony\Component\HttpFoundation\File\File $comprobante_file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComprobanteFile', [$comprobante_file]);

        return parent::setComprobanteFile($comprobante_file);
    }

    /**
     * {@inheritDoc}
     */
    public function getComprobante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComprobante', []);

        return parent::getComprobante();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', []);

        return parent::getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuario(\SalexUserBundle\Entity\User $idusuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuario', [$idusuario]);

        return parent::setIdusuario($idusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setComprobante($comprobante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComprobante', [$comprobante]);

        return parent::setComprobante($comprobante);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionmov($descripcionmov)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionmov', [$descripcionmov]);

        return parent::setDescripcionmov($descripcionmov);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionmov()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionmov', []);

        return parent::getDescripcionmov();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonto($monto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonto', [$monto]);

        return parent::setMonto($monto);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonto', []);

        return parent::getMonto();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadomov($estadomov)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadomov', [$estadomov]);

        return parent::setEstadomov($estadomov);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadomov()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadomov', []);

        return parent::getEstadomov();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmov()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdmov();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmov', []);

        return parent::getIdmov();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcuenta(\AppBundle\Entity\Cuenta $idcuenta = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcuenta', [$idcuenta]);

        return parent::setIdcuenta($idcuenta);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcuenta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcuenta', []);

        return parent::getIdcuenta();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtipomov(\AppBundle\Entity\Tipomovimiento $idtipomov = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtipomov', [$idtipomov]);

        return parent::setIdtipomov($idtipomov);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtipomov()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtipomov', []);

        return parent::getIdtipomov();
    }

    /**
     * {@inheritDoc}
     */
    public function onPrePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', []);

        return parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function onPreUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPreUpdate', []);

        return parent::onPreUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateAt($updateAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateAt', [$updateAt]);

        return parent::setUpdateAt($updateAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateAt', []);

        return parent::getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

}
