<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Transaccioncolaboracion extends \AppBundle\Entity\Transaccioncolaboracion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'idtransaccolaboracion', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'fechatransaccolabora', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'descripciontransaccolabora', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'tipotransaccolabora', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'montotrasaccolabora', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'estadotransaccolabora', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'mespagotransaccolabora', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'idtipotransaccion', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'idcolaboracion'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'idtransaccolaboracion', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'fechatransaccolabora', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'descripciontransaccolabora', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'tipotransaccolabora', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'montotrasaccolabora', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'estadotransaccolabora', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'mespagotransaccolabora', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'idtipotransaccion', '' . "\0" . 'AppBundle\\Entity\\Transaccioncolaboracion' . "\0" . 'idcolaboracion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Transaccioncolaboracion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setFechatransaccolabora($fechatransaccolabora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechatransaccolabora', [$fechatransaccolabora]);

        return parent::setFechatransaccolabora($fechatransaccolabora);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechatransaccolabora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechatransaccolabora', []);

        return parent::getFechatransaccolabora();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripciontransaccolabora($descripciontransaccolabora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripciontransaccolabora', [$descripciontransaccolabora]);

        return parent::setDescripciontransaccolabora($descripciontransaccolabora);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripciontransaccolabora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripciontransaccolabora', []);

        return parent::getDescripciontransaccolabora();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipotransaccolabora($tipotransaccolabora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipotransaccolabora', [$tipotransaccolabora]);

        return parent::setTipotransaccolabora($tipotransaccolabora);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipotransaccolabora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipotransaccolabora', []);

        return parent::getTipotransaccolabora();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontotrasaccolabora($montotrasaccolabora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontotrasaccolabora', [$montotrasaccolabora]);

        return parent::setMontotrasaccolabora($montotrasaccolabora);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontotrasaccolabora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontotrasaccolabora', []);

        return parent::getMontotrasaccolabora();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadotransaccolabora($estadotransaccolabora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadotransaccolabora', [$estadotransaccolabora]);

        return parent::setEstadotransaccolabora($estadotransaccolabora);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadotransaccolabora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadotransaccolabora', []);

        return parent::getEstadotransaccolabora();
    }

    /**
     * {@inheritDoc}
     */
    public function setMespagotransaccolabora($mespagotransaccolabora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMespagotransaccolabora', [$mespagotransaccolabora]);

        return parent::setMespagotransaccolabora($mespagotransaccolabora);
    }

    /**
     * {@inheritDoc}
     */
    public function getMespagotransaccolabora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMespagotransaccolabora', []);

        return parent::getMespagotransaccolabora();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtransaccolaboracion()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdtransaccolaboracion();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtransaccolaboracion', []);

        return parent::getIdtransaccolaboracion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcolaboracion(\AppBundle\Entity\Colaboracionmonetaria $idcolaboracion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcolaboracion', [$idcolaboracion]);

        return parent::setIdcolaboracion($idcolaboracion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcolaboracion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcolaboracion', []);

        return parent::getIdcolaboracion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtipotransaccion(\AppBundle\Entity\Tipotransaccion $idtipotransaccion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtipotransaccion', [$idtipotransaccion]);

        return parent::setIdtipotransaccion($idtipotransaccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtipotransaccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtipotransaccion', []);

        return parent::getIdtipotransaccion();
    }

}
